### ISSUE TITLE
define index.html in serve script

### ISSUE THREAD

**Issue by knuspertante** [lit/lit-element-starter-ts#32]
currently the serve script does not define the respective index.html

change
`"serve": "es-dev-server --node-resolve --watch "`

to
`"serve": "es-dev-server --app-index dev/index.html --node-resolve --watch --open"`

**Comment by AndrewJakubowicz** [comment]
This should be addressed after [this change](https://github.com/lit/lit/commit/8b9dcb4d10e4161083146ae40d0b12174a63d31d) is released.

There is a bug where currently `npm run serve` is serving the documentation directory instead of your demo.

I'll follow up on this thread once the starter kits have had a new release.
Thank you!

**Comment by AndrewJakubowicz** [comment]
Sorry for the slow turnaround. I believe this issue has been addressed with https://github.com/lit/lit-element-starter-ts/commit/43c1dfb1c9444ca621aced60640e5bd8dfa36182. `npm run serve` will now guide you to where your component is defined.
Thank you!
